### ISSUE TITLE
"Generate Summary" functionality if I want to view summary of the current session actions

### ISSUE THREAD

**Issue by 4tal** [All-Hands-AI/OpenHands#2349]
**What problem or use case are you trying to solve?**

Understand what are the actions that have been done so far.

**Describe the UX of the solution you'd like**

Remove the need to scroll, copy all the pages, go to ChatGPT, and get a summary.

**Comment by mamoodi** [comment]
Hello are you able to clarify this issue a little more please?

You've asked the agent to perform some tasks. Now you don't want to scroll to see what the agent has done. You want to go somewhere so that it can be summarized what the agent has done? So if it's coding, you want it to summarize the actions it performed in a TLDR?

**Comment by 4tal** [comment]
@mamoodi Yes, the idea is to have the ability to view a summary of what has been done so far after giving the AI multiple tasks or a complex task. This summary would be TLDR++; it would be a structured overview of the actions taken, decisions made, and current status of the task(s). It's kind of filtered UI action logs.

**Comment by enyst** [comment]
@4tal Thank you for the suggestion. In a way, the user can always have a summary, since the current default agent, CodeAct, has natively the ability to chat with the user. It stops quite a bit during its tasks, and waits for further input, feedback or task. You can ask to tell what it has done so far. It's a bit limited right now, but we're working on it!

Another option would be a progress view, with steps like "figuring out the repository layout...I have figured out the repository layout." Basically a Planning view, which is updated as the agent does stuff. Do you think that would be suitable for this feature?
