### ISSUE TITLE
Enable memgpt

### ISSUE THREAD

**Issue by rezzie-rich** [All-Hands-AI/OpenHands#2487]
Is it possible to create a memgpt feature and make it available to all the agents rather than having a separate agent like it's discussed in #530?

**Comment by FellowTraveler** [comment]
Can you elaborate on what this would entail?

**Comment by rezzie-rich** [comment]
Currently, there is a problem with the LLM's context window. Models with small context windows stand no chance against models with 128k+ window. There is already a short & long-term memory system integrated. However, i don't think that memory is encoded and discipte the current memory structure context window is still an issue. I did see an attempt to add a separate memgpt-agent as discussed on #530. It would be great if the memgpt features can be integrated into all the agents so the context window of an llm becomes irrelevant. 


Theoretically, output generated by a 4k window model can also be stored in the short-term memory, so when the model continues to generate response after reaching max token, it can successfully pickup where it left off without getting lost.

**Comment by neubig** [comment]
Yeah, I think this is a better way to implement MemGPT. I think I'll actually close the previous issue because having a "MemGPT Agent" doesn't really make sense.

I would like to note that we already have a PR open for [MemGPT-like functionality](https://github.com/OpenDevin/OpenDevin/pull/2021), the memory condenser.

However, MemGPT was built specifically for this purpose, so it may be worth incorporating MemGPT as an alternative version of the memory condenser that could be swapped in for #2021. I think the architecture could be largely similar.

**Comment by neubig** [comment]
Hey @rezzie-rich ! Just to clarify, I think we'd be very excited to have a contribution implementing memgpt in OpenDevin, and would like to benchmark it against other approaches. I think the #2021 actually creates some general purpose infrastructure for short-term and long-term memory, and memgpt could be substituted in for the memory condenser that is in there.

**Comment by khushvind** [comment]
Hey @neubig ! I have started working on this issue.

**Comment by khushvind** [comment]
Yeah, we should also add that. I think giving more weightage to user inputs can be a good start. Current implementation, https://github.com/OpenDevin/OpenDevin/pull/2937 gives equal importance to all the message, and can lose the context of the actual task given by user after some summarizations.

I'm not much familiar with it, is there any prior work or study on methods to classify the importance of agent messages?

**Comment by enyst** [comment]
This is a very good point. One thing we were trying was to keep user messages for longer time, to make sure we don't lose the task with whatever the user may have specified. That was rather rough, and it doesn't concern agent messages.

Current implementation has a `condensable` flag on messages, that would in theory allow us to make a decision to keep some, but it doesn't atm choose to keep any other than the system message and something like it.

I've done some work on prompts that would make the LLM, during summarization, choose in a more appropriate manner, that is, considering the importance to some messages in function of both time and contents, but it wasn't systematic, not clearly better, and anyway it was for the old agent (not CodeAct). Maybe you're right that it would work better to separate the two: have an LLM make a pass and assign weights, then perform the summarization. Or maybe a better step-by-step prompt.

I think currently we just need to make sure that the summaries are detailed enough that they do keep information, such that the agent is guided forward helpfully. I am yet to test @khushvind 's prompts on the SWE-bench tasks, but I'll get to do that. If you wish to try it, it's PR #2937

**Comment by 0xdevalias** [comment]
It's been a while since I was thinking deeply in this space; but I remember ages back seeing some stuff described by Dave Shapiro around memory; using a sort of tree-like structure, where the it sort of abstracted to higher level summaries as it went up.

Trying to find the blog/video/whatever it was but currently failing. I believe the idea was to be able to use the higher level summaries to get the RAG-like aspect into the right 'area'; and then can 'drill down' for more specific memory context if needed.

There was also some stuff I remember him describing about 'sparse priming representations'; which from what I remember was basically like.. compressing the prompt/etc into a form that the LLM is able to still get the same context back from it, but without using as many tokens; essentially 'getting it into the right state of mind' so to speak.

I wonder if these concepts might be useful here; probably alongside the 'multiple streams of thought' and 'memory curator' aspects described above (as at face value; they sound like a pretty good approach to me)

**Comment by enyst** [comment]
We did that in the past, in the first agent (monologue), we were embedding every event as soon as it was happening, and prompting the LLM to know how to retrieve it if necessary. Currently there is no mechanism for CodeAct.

**Comment by enyst** [comment]
Monologue agent hasn't been tested without embeddings, I don't think, but FWIW there's no reason to result in loss of context because of it (it doesn't lose anything to embed stuff). Instead, it's possible it didn't solve losses from summarization well enough. FWIW, in my opinion, it wasn't making a significant difference on performance, but it helped with user experience: longer sessions!

**Comment by enyst** [comment]
I don't follow, sorry, I think there is a misunderstanding here. Embedding text doesn't change the text, it just creates a vector, which is then stored it in a vector database, to be retrieved later.

**Comment by enyst** [comment]
@rezzie-rich What the LLM seems to be saying is a non-issue here, don't worry about it. 😄 

You may want to keep in mind that LLMs are trained to 1) say the words that best follow the words of the user, and 2) give the user what they want. If you prompt it appropriately, it'll happily answer the opposite. 😅

Back to the issue at hand, we will add both mechanisms eventually. Please feel free to test the linked PR when it's stable, to see how it works for you, your feedback would be appreciated!

**Comment by 0xdevalias** [comment]
RE: https://github.com/OpenDevin/OpenDevin/issues/2487#issuecomment-2254833846

> this describes a vector database where texts are converted into numbers and stored in a relational high-dimensional space.

@rezzie-rich That's not what the 'Sparse Priming Representation' stuff is about. It's more about abstracting/summarizing the key points from the supplied text, while removing any 'irrelevant boilerplate' / wasted tokens / etc. You can see the methodology in the prompts:

- https://github.com/daveshap/SparsePrimingRepresentations#spr-generator
- https://github.com/daveshap/SparsePrimingRepresentations#spr-decompressor

Obviously that may still not be useful/relevant here, but I want to make sure we're at least not discounting it based on false assumptions.
