### ISSUE TITLE
[Bug]: Using a port other than 3000 on the client breaks LLM setup on :main

### ISSUE THREAD

**Issue by jriff** [All-Hands-AI/OpenHands#4344]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

When running the docker command with eg. ` -p 3001:3000`, the LLM setup breaks as seen on this screenshot:

<img width="479" alt="Screenshot 2024-10-11 at 08 28 25" src="https://github.com/user-attachments/assets/d538aeb4-6b62-4e85-986d-fa77eb7c831c">

I can't choose anything in the drop-downs. I just see "verified" and "others" but none of them are clickable. I don't know if this is a known issue. It happens both in Safari and Chrome on Mac.

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

MacOS

**Comment by amanape** [comment]
If hostname is `localhost`, the server fallback URL to communicate with the backend is always `localhost:3000`. This is incorrect in your scenario since the server is now running on `localhost:3001`.

https://github.com/All-Hands-AI/OpenHands/blob/caa77cf7a6c1a94ea2b51357967c4646d00edad8/frontend/src/utils/get-valid-fallback-host.ts#L12-L20

For now, you can run OpenHands locally (pull and run `make build && make run`). Feel free to set the environment variable to whichever URL you need here:
https://github.com/All-Hands-AI/OpenHands/blob/caa77cf7a6c1a94ea2b51357967c4646d00edad8/frontend/.env.sample#L1

Note that in this mode, the frontend is expected to be served on `localhost:3001`, another limitation but its because:
https://github.com/All-Hands-AI/OpenHands/blob/caa77cf7a6c1a94ea2b51357967c4646d00edad8/openhands/server/listen.py#L79

Will create an issue for this soon, feel free to submit a PR to fix these if you're up for it 😃
