### ISSUE TITLE
Update e2b

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#4443]
**Summary**

We use e2b 0.17, and it is at 1.x now. It seems that with the major version, it has a number of incompatible changes. I think we need to look into them and do this upgrade manually:

- https://github.com/All-Hands-AI/OpenHands/pull/4432

**Comment by neubig** [comment]
I got a report from a user:
* In https://github.com/All-Hands-AI/OpenHands/blob/fdb385ab93b9c6768f62a5ee5f8df87bcdbd0107/openhands/runtime/impl/e2b/sandbox.py#L7, I think it should be from e2b.exceptions import instead of from e2b.sandbox.exception import now. There might be an upgrade in e2b that changes this.
