### ISSUE TITLE
[Bug]: Errors in js console after disabling posthog

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#4797]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Running locally, I got the pop-up to ask about posthog, and disabled it. Then as the app is starting up, the js console is a bit unhappy:

![Screenshot 2024-11-06 at 19 59 45](https://github.com/user-attachments/assets/3e61ab55-bbc8-4bb5-940e-7dccddaff75d)

The browser is Brave. Shouldn't it not try to connect? Cc: @amanape 

### OpenHands Installation

Development workflow

### Operating System

None

**Comment by amanape** [comment]
Yes I've noticed this too and confirmed a few times that no events are being logged. I'll look into why exactly its logging soon though

**Comment by amanape** [comment]
So it turns out that this is due to the ad-blocker. You can confirm that they stop after disabling the ad-blocker. 

It has something to do when we init PostHog (before opting in or out):
https://github.com/All-Hands-AI/OpenHands/blob/1725627c7d25b089fbdd7697eaa1ba3143f6bb0a/frontend/src/entry.client.tsx#L25-L28

I assume it tries to make initial contact with the `api_host` (https://us.i.posthog.com) but fails to do so because of the ad-blocker, so it attempts to retry. They don't seem to have configurations to handle this error though so not much I can do ☹️ 

Feel free to re-open this issue if you still encounter it after disabling ad-block
