### ISSUE TITLE
[Bug]: time out keeps occur , replacement of docker if possible too 

### ISSUE THREAD

**Issue by al3ahel** [All-Hands-AI/OpenHands#4877]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

after running it i face this problem 

$ npx create-expo-app app --template blank
Need to install the following packages:
create-expo-app@3.0.0
Ok to proceed? (y) 
npm error canceled
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-09T18_37_19_512Z-debug-0.log

[Command timed out after 120 seconds. SIGINT was sent to interrupt the command.]

$ 

### OpenHands Installation

Docker command in README

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

after running it i face this problem 

$ npx create-expo-app app --template blank
Need to install the following packages:
create-expo-app@3.0.0
Ok to proceed? (y) 
npm error canceled
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-11-09T18_37_19_512Z-debug-0.log

[Command timed out after 120 seconds. SIGINT was sent to interrupt the command.]

$

**Comment by bbarclay** [comment]
I always tell it. DO NOT RUN THESE COMMANDS. 

[Command timed out after 120 seconds. SIGINT was sent to interrupt the command, but failed. The command was killed.]

$ npx nx test chat --verbose

[1]+  Stopped                 npx nx test chat --verbose

[1]+  Stopped                 npx nx test chat --verbose


[Command timed out after 120 seconds. SIGINT was sent to interrupt the command, but failed. The command was killed.]



The problem is. 


and how you get around it. 


You tell it to run it as a background process an write it to a log. 


The reason this happens, is because it's a post request. If that post request is VOID. or hangs or gets to a terminal command that would need stopped. Then it hangs.

**Comment by al3ahel** [comment]
> I always tell it. DO NOT RUN THESE COMMANDS. 
> 
> [Command timed out after 120 seconds. SIGINT was sent to interrupt the command, but failed. The command was killed.]
> 
> $ npx nx test chat --verbose
> 
> [1]+  Stopped                 npx nx test chat --verbose
> 
> [1]+  Stopped                 npx nx test chat --verbose
> 
> 
> [Command timed out after 120 seconds. SIGINT was sent to interrupt the command, but failed. The command was killed.]
> 
> 
> 
> The problem is. 
> 
> 
> and how you get around it. 
> 
> 
> You tell it to run it as a background process an write it to a log. 
> 
> 
> The reason this happens, is because it's a post request. If that post request is VOID. or hangs or gets to a terminal command that would need stopped. Then it hangs. 
> 
> 
> 
> 
> 

But it run it directly from the AI to install packages of Expo sdk and node

**Comment by mamoodi** [comment]
Yeah this is a known issue and not sure if the behavior will change for now.
If a command you will run is going to take longer than 2 minutes, you can modify the timeout by passing this to your docker command:

For example below sets the timeout to 5 minutes.
```
-e SANDBOX_TIMEOUT=300
```

But yes this is an issue I've run into multiple times.
