### ISSUE TITLE
it is run on colab

### ISSUE THREAD

**Issue by werruww** [All-Hands-AI/OpenHands#4917]
!pip install udocker

!udocker --allow-root install

!udocker --allow-root pull docker.all-hands.dev/all-hands-ai/openhands:main

!udocker --allow-root run docker.all-hands.dev/all-hands-ai/openhands:main

ollama on colab

!pip install colab-xterm #https://pypi.org/project/colab-xterm/
%load_ext colabxterm

%xterm

!curl -fsSL https://ollama.com/install.sh | sh

!pip install pyngrok

from pyngrok import ngrok

# Set the authentication token
ngrok.set_auth_token("xxxxxxxxxxxxxxxxxxxxxxx")

# Open an ngrok tunnel to the Gazebo server port (11345)
public_url = ngrok.connect(3000)
print("Public URL:", public_url)

**Comment by werruww** [comment]
from pyngrok import ngrok
ngrok.set_auth_token("xxxxxxxxxxxxxxxxxxxxxxx")
public_url = ngrok.connect(3000)
print("Public URL:", public_url)

**Comment by werruww** [comment]
![Untitled](https://github.com/user-attachments/assets/f5398ae5-ef04-46b2-8575-5b2a425ec082)

**Comment by werruww** [comment]
![Unti2tled](https://github.com/user-attachments/assets/11a510c0-6043-4113-8bcd-e4949f6b3e26)
![Unti3tled](https://github.com/user-attachments/assets/9ae15237-bf94-4de6-9e7f-1243361d12a9)

**Comment by werruww** [comment]
![Un4titled](https://github.com/user-attachments/assets/20536599-e8e9-4d79-8694-ec7902f5406c)

**Comment by werruww** [comment]
![error](https://github.com/user-attachments/assets/cf6e499b-7e1e-4267-9218-dcaf65db0a1f)

**Comment by werruww** [comment]
nneed python 3.12


pytjhon colab 3.10


# إنشاء بيئة Python 3.12
!/usr/local/miniconda/bin/conda create -y -n openhands_env python=3.12


# تشغيل الأمر داخل بيئة openhands_env
!/usr/local/miniconda/bin/conda run -n openhands_env python --version


# تثبيت مكتبة معينة داخل البيئة
!/usr/local/miniconda/bin/conda run -n openhands_env pip install library_name

# تشغيل كود Python داخل البيئة
!/usr/local/miniconda/bin/conda run -n openhands_env python your_script.py

**Comment by werruww** [comment]
# تحميل وتثبيت Miniconda
!wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash miniconda.sh -b -p /usr/local/miniconda


# إنشاء بيئة Python 3.12
!/usr/local/miniconda/bin/conda create -y -n openhands_env python=3.12

# تفعيل البيئة بشكل مباشر
!source /usr/local/miniconda/etc/profile.d/conda.sh && conda activate openhands_env

**Comment by werruww** [comment]
!pip install -q condacolab
import condacolab
condacolab.install()

!conda install -c conda-forge python=3.12

**Comment by werruww** [comment]
![Unt5itled](https://github.com/user-attachments/assets/a518fcba-5b2a-4c28-b49f-0d3297622b30)

**Comment by werruww** [comment]
There are errors, and the form did not run, and I think the name of the form is wrong. Also, the Python version is an error that must be downloaded through Conda. It does not matter that Docker contener ran in Colab.

**Comment by wzircom** [comment]
لدي نفس التجربه على Cloud Shell Terminal
`Welcome to Cloud Shell! Type "help" to get started.
Your Cloud Platform project in this session is set to mypanel-1697xxxxxx739.
Use “gcloud config set project [PROJECT_ID]” to change to a different project.
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ curl -o udocker.tar.gz https://github.com/indigo-dc/udocker/releases/download/1.3.8/udocker-1.3.8.tar.gz
tar -xvzf udocker.tar.gz
chmod u+x udocker
sudo mv udocker /usr/local/bin/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chmod: cannot access 'udocker': No such file or directory
mv: cannot stat 'udocker': No such file or directory
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ curl -o udocker.tar.gz https://github.com/indigo-dc/udocker/releases/download/1.3.8/udocker-1.3.8.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ ls -lh udocker.tar.gz
-rw-rw-r-- 1 myCloudshell myCloudshell 0 Nov 19 02:40 udocker.tar.gz
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ pip install udocker
Defaulting to user installation because normal site-packages is not writeable
Collecting udocker
  Downloading udocker-1.3.17-py2.py3-none-any.whl.metadata (37 kB)
Downloading udocker-1.3.17-py2.py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.6/119.6 kB 5.1 MB/s eta 0:00:00
Installing collected packages: udocker
  WARNING: The script udocker is installed in '/home/myCloudshell/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed udocker-1.3.17
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ curl -fsSL https://raw.githubusercontent.com/indigo-dc/udocker/master/udocker.py -o udocker
chmod +x udocker
./udocker --help
curl: (22) The requested URL returned error: 404
chmod: cannot access 'udocker': No such file or directory
-bash: ./udocker: No such file or directory
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ /home/myCloudshell/.local/bin
-bash: /home/myCloudshell/.local/bin: Is a directory
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ export PATH=$PATH:/home/myCloudshell/.local/bin
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ udocker --help
Info: creating repo: /home/myCloudshell/.udocker

Syntax:
  udocker  [general_options] <command>  [command_options]  <command_args>

  udocker [-h|--help|help]        :Display this help and exits
  udocker [-V|--version|version]  :Display udocker and tarball version and exits

General options common to all commands must appear before the command:
  -D, --debug                   :Debug
  -q, --quiet                   :Less verbosity
  --insecure                    :Allow insecure non authenticated https
  --repo=<directory>            :Use repository at directory
  --allow-root                  :Allow execution by root NOT recommended
  --config=<conf_file>          :Use configuration <conf_file>

Commands:
  --help [command]              :Command specific help
  showconf                      :Print all configuration options

  search <repo/expression>      :Search dockerhub for container images
  pull <repo/image:tag>         :Pull container image from dockerhub
  create <repo/image:tag>       :Create container from a pulled image
  run <container_id|name>       :Execute created container
  run <repo/image:tag>          :Pull, create and execute container

  images -l                     :List container images
  ps -m -s                      :List created containers
  name <container_id> <name>    :Give name to container
  rmname <name>                 :Delete name from container
  rename <name> <new_name>      :Change container name
  clone <container_id>          :Duplicate container
  rm  <container-id|name>       :Delete container
  rmi <repo/image:tag>          :Delete image
  tag <repo/image:tag> <repo2/image2:tag2> :Tag image

  import <tar> <repo/image:tag> :Import tar file (exported by docker)
  import - <repo/image:tag>     :Import from stdin (exported by docker)
  export -o <tar> <container>   :Export container directory tree to file
  export - <container>          :Export container directory tree to stdin
  load -i <exported-image>      :Load image from file (saved by docker)
  load                          :Load image from stdin (saved by docker)
  save -o <imagefile> <repo/image:tag>  :Save image with layers to file

  inspect -p <repo/image:tag>   :Print image or container metadata
  verify <repo/image:tag>       :Verify a pulled image
  manifest inspect <repo/image:tag> :Print manifest metadata

  udocker manifest inspect centos/centos8
  udocker pull --platform=linux/arm64 centos/centos8
  udocker tag centos/centos8  mycentos/centos8:arm64

  protect <repo/image:tag>      :Protect repository
  unprotect <repo/image:tag>    :Unprotect repository
  protect <container>           :Protect container
  unprotect <container>         :Unprotect container

  mkrepo <top-repo-dir>         :Create another repository in location
  setup --execmode=<mode>       :Change container execution mode
  setup --nvidia                :Setup container to use nvidia GPU
  setup --purge                 :clean mountpoints and files created by udocker
  setup --fixperm               :attempt to fix file permissions

  login                         :Login into docker repository
  logout                        :Logout from docker repository

Examples:
  udocker search expression
  udocker search quay.io/expression
  udocker search --list-tags myimage
  udocker pull myimage:mytag
  udocker images
  udocker create --name=mycontainer  myimage:mytag
  udocker ps -m -s
  udocker inspect mycontainer
  udocker inspect -p mycontainer

  udocker manifest inspect centos/centos8
  udocker pull --platform=linux/arm64 centos/centos8
  udocker tag centos/centos8  mycentos/centos8:arm64

  udocker run  mycontainer  cat /etc/redhat-release
  udocker run --hostauth --hostenv --bindhome  mycontainer
  udocker run --user=root  mycontainer  yum install firefox
  udocker run --hostauth --hostenv --bindhome mycontainer  firefox
  udocker run --entrypoint="" mycontainer  /bin/bash -i
  udocker run --entrypoint="/bin/bash" mycontainer -i

  udocker clone --name=anotherc mycontainer
  udocker rm anotherc

  udocker mkrepo /data/myrepo
  udocker --repo=/data/myrepo load -i docker-saved-repo.tar
  udocker --repo=/data/myrepo images
  udocker --repo=/data/myrepo run --user=$USER  myimage:mytag

  udocker export -o myimage.tar mycontainer
  udocker import myimage.tar mynewimage
  udocker create --name=mynewc mynewimage
  udocker export --clone -o mycontainer.tar mycontainer
  udocker import --clone mycontainer.tar

Notes:
 * by default the binaries, images and containers are placed in
      $HOME/.udocker
 * by default the following host directories are mounted in the
   container:
      /dev /proc /sys /etc/resolv.conf /etc/host.conf /etc/hostname
 * to prevent the mount of the above directories use:
      run  --nosysdirs  <container>
 * additional host directories to be mounted are specified with:
      run --volume=/data:/mnt --volume=/etc/hosts  <container>
      run --nosysdirs --volume=/dev --volume=/proc  <container>
 * udocker provides several execution modes that offer different
   approaches and technologies to execute containers, they
   can be selected using the setup command. See the setup help.
      udocker setup --execmode=F3 fedx
      udocker setup --execmode=R1 fedx
      udocker setup --execmode=S1 fedx
      udocker setup --help
 * udocker facilitates the usage of nvidia drivers within containers
      udocker setup --nvidia fedx

See: https://github.com/indigo-dc/udocker/blob/master/SUMMARY.md
            
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ udocker pull docker.all-hands.dev/all-hands-ai/openhands:main
Info: udocker command line interface 1.3.17
Info: searching for udockertools >= 1.2.11
Info: installing udockertools 1.2.11
Info: installation of udockertools successful
Info: downloading layer sha256:31df8c89801ed6cf67e7dd0cdcec791f882aa816a3770ee7d1c84618c0bdf977
Info: downloading layer sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Info: downloading layer sha256:b733bed20b4a0d56bc143fedd27a5ec3f030a7779344dc7cd7ef9bcc2004ced5
Info: downloading layer sha256:384e783897374454dd2d9ce125ad4fa69751339ab3674e4bb6437e8cf2e9e180
Info: downloading layer sha256:9f1d5cf1459abc8c45945b26c02100fdc10d8f408c8ade381e8a3afc28b3f647
Info: downloading layer sha256:cdc6f662e24f6d3456857f44e94262d54463a3e64bc9ec4e333d47060a03e217
Info: downloading layer sha256:64822f44b0e4d7cd44ceb6ca88b2c2e0dffb49113db40e240e5c025c05272b5b
Info: downloading layer sha256:dcd4a30b529336cc605552d79a48aa7a68bc6041c8a9121ee4401fca865d3058
Info: downloading layer sha256:cf1e776c7fa493be8d03127c56efc47171e8f3d5b644f75b4ef07735f74b47ef
Info: downloading layer sha256:da39a60b3831f939720a12db332a6ab67b619c49ddd930e78c96c3349b2b0a97
Info: downloading layer sha256:e1bdda0c2a7d00d69a70f2b42300bc90782a5d894e7261cb3ece1b569673b523
Info: downloading layer sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Info: downloading layer sha256:c052ffdcfea8f108c12232ccbf75615239fa20bf963ef1f67f8411281640e409
Info: downloading layer sha256:3770f77288f805c3e1fc1c4c0b51cde979b09157c98d5ae09595f0bbeb7e5618
Info: downloading layer sha256:686191747126216f8bc4167c2e3dd42d6ce3a2deff816bfc6d3edf9a106f7dce
Info: downloading layer sha256:4b8c781c9119ab670f306d28dec50cb3c2c77e0ffb670eb4ed2747b5653ab44d
Info: downloading layer sha256:9cd53115a1a175b22c4bb78c841351da82c2e9b60166085d6071c0416d6191ba
Info: downloading layer sha256:c0af04535154beb57471320aedfe3832b19f67dd3339e235aee84ca0478f83aa
Info: downloading layer sha256:fa94b540fe0c87d7f1e492729c54c984f4d8721649f080740f38ae4e6a643027
Info: downloading layer sha256:e18b86bcc1cde8ea5e07ed7b39aee9af4e845acd1f77312cc22fe56577672840
Info: downloading layer sha256:09c97771a32f89d37375750ddac8e6c33abe3b1e7669d666054c7a8da42c185b
Info: downloading layer sha256:a04f34443c0d1fe158c61005471885b99d8bbb1591fe2c898b35c02fda4304dc
Info: downloading layer sha256:18234a9e9c0093b678301551c3188a6f4f330b1b07f9a86c7842fd9a627618dc
Info: downloading layer sha256:f802123ace98d25e865395da4a72bbe7ba3788d9b0d8fef5ea21630b5bc046b0
Info: downloading layer sha256:0edbbd94250f81bbf65845e269abb088989c3cb518f050f88c119e093631cd1d
Info: downloading layer sha256:3cf9507408dcb24084c3a20ccd068986cc37d1b13629d357f402581af5177013
Info: downloading layer sha256:ded8879d9a790c3944bc22c2bed1606a9a2d4d293f2a32399fb183d577c0190a
Info: downloading layer sha256:2e133733af76c2a11aee79b7cfc733cc8065bc538d74b80ad65846d336a0904e
Info: downloading layer sha256:276709cbedc1f168290ee408fca2af2aacfeb4f922ddca125e9e8047f9841479
Info: downloading layer sha256:09f376ebb190216b0459f470e71bec7b5dfa611d66bf008492b40dcc5f1d8eae
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ pip install --user pyngrok
Collecting pyngrok
  Downloading pyngrok-7.2.1-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.2)
Downloading pyngrok-7.2.1-py3-none-any.whl (22 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-7.2.1
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ from pyngrok import ngrok
-bash: from: command not found
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ python3
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> 
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ nano ngrok_script.py
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ python3 ngrok_script.py
Public URL: NgrokTunnel: "https://dcad-xxxxxx-xxxxxx-xxxxxx-xxxxxx.ngrok-free.app" -> "http://localhost:3000"     
myCloudshell@cloudshell:~ (mypanel-1697xxxxxx739)$ udocker run docker.all-hands.dev/all-hands-ai/openhands:main
 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING 21ca8b22-2dc0-34aa-86d1-f449532f6e66                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: entrypoint.sh
Starting OpenHands...
Running OpenHands as root
INFO:     Started server process [1466]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     156.206.1.90:0 - "GET / HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/manifest-9046639b.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/root-CG37RII1.css HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/router-CQIzOUUf.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/open-hands-DHJpScOq.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/codeSlice-wI_EoNV2.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/AgentState-DCyv5jZT.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/store-DXTsEru2.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/root-DjGxIpac.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/cache-CGyOfnUE.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/index-q04i6vPp.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/entry.client-ChCoHn85.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/i18nInstance-BhwiS_NP.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/jsx-runtime-zhgTtAea.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/components-B5Tcp_HM.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/index-DW5fD9dL.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/module-DcwBQ7rW.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/agentSlice-0xeL04tr.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /locales/ar/translation.json HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /locales/en/translation.json HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /locales/ar-EG/translation.json HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/_oh-Clnc_Che.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /config.json HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/route-C9jQHtim.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/responses-iq082X3z.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/connect-to-github-modal-DOlmGON6.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/utils-p7Tk_-vA.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/declaration-BheR2oEq.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/github-logo-BruGP2oe.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/modal-backdrop-D22Qdxdj.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/extends-CEetKkoc.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/settings-DawUpo-u.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/LoadingProject-B0fD2l0z.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /api/options/security-analyzers HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/set-consent-DWbcphLP.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/settings-53ET1LPM.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/_oh.app-uPZuECOb.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/route-B94b1vlk.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/_oh.app-oQm45wwO.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/index-lsr95zsB.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/useScrollToBottom-B8_iP14x.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/iconBase-rNSBfUUz.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/index-BfUcQcX0.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/index-CVhOlqYX.js HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/Terminal-CGrrDQr5.css HTTP/1.1" 200 OK
INFO:     156.206.1.90:0 - "GET /assets/Terminal-gsY-Km17.js HTTP/1.1" 200 OK
INFO:     ('156.206.1.90', 0) - "WebSocket /ws" [accepted]
02:54:15 - openhands:INFO: listen.py:341 - New session: d9ac89cd-c291-4c45-8638-13fcfa515eca
INFO:     connection open
02:54:16 - openhands:INFO: codeact_agent.py:87 - Function calling not enabled for model gemini/gemini-1.5-flash-latest. Mocking function calling via prompting.
02:54:16 - openhands:ERROR: eventstream_runtime.py:266 - Launch docker client failed. Please make sure you have installed docker and started docker desktop/daemon.
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=DockerException("Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))")>
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/app/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/.venv/lib/python3.12/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 223, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 246, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 92, in _start_thread
    asyncio.run(self._start(*args), debug=True)
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/openhands/server/session/agent_session.py", line 108, in _start
    await self._create_runtime(
  File "/app/openhands/server/session/agent_session.py", line 186, in _create_runtime
    self.runtime = runtime_cls(
                   ^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 175, in __init__
    self.docker_client: docker.DockerClient = self._init_docker_client()
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 269, in _init_docker_client
    raise ex
  File "/app/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 264, in _init_docker_client
    return docker.from_env()
           ^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 94, in from_env
    return cls(
           ^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 207, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/docker/api/client.py", line 230, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
`
