### ISSUE TITLE
[Bug]: Editing Error "No replacement was performed" is not informative enough

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5365]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The agent got this error:
```
ERROR:
No replacement was performed. Multiple occurrences of old_str `            output_path = Path.joinpath(self._output_dir, "recipe_state.pt")
            torch.save(state_dict, output_path)
            logger.info(
                "Recipe checkpoint of size "
                f"{os.path.getsize(output_path) / 1000**3:.2f} GB "
                f"saved to {output_path}"
            )` in lines []. Please ensure it is unique.
```

`in lines []. Please ensure it is unique.` does look right? Should we give out the specific line number?

Full trajectory: https://www.all-hands.dev/share?share_id=7c05665906ffb699d93426129b1ee8c50c3cc5c7dcb5e164de9c54f6468e7876

cc @ryanhoangt

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by enyst** [comment]
Just to note for the record, this is from Anthropic's [error strings for the LLM](https://github.com/anthropics/anthropic-quickstarts/blob/c4b5d1e4149bc28275382205a2fcfa27a7e76129/computer-use-demo/computer_use_demo/tools/edit.py#L177)

When I saw the LLM do many of these, and fail because of max iterations, I had to use this prompt:
https://github.com/All-Hands-AI/OpenHands/pull/5223#issuecomment-2495653514

It worked so well I had to jump for joy (no, really 😅)

> You're good! Your choice to run bash scripts was brilliant!
> You fixed the rest of the documentation for human users in only 4 steps this time.

**Comment by ryanhoangt** [comment]
Fixing PR raised: https://github.com/All-Hands-AI/openhands-aci/pull/17

**Comment by avi12** [comment]
Occurs again in 0.17 with GPT-4o:
![image](https://github.com/user-attachments/assets/3a82f811-a1a3-4f12-93ac-65a4b0ef115c)

**Comment by avi12** [comment]
Apparently as of commenting, OpenAI has a major [outage](https://status.openai.com/incidents/6bwlxnvdncnm)
![image](https://github.com/user-attachments/assets/6f212bfb-096c-4f2f-a100-f5183ce162af)
