### ISSUE TITLE
Is openhands the right framework if you want a fully autonomous agent? Assuming the base LLM is good enough of course. 

### ISSUE THREAD

**Issue by JustinMBrown** [All-Hands-AI/OpenHands#5429]
**Summary**

Fully Autonomous agent that only stops if it wants input from the user, or thinks it completed the task

**Motivation**

With o1, I was able to describe the program I wanted, and instructed it to ask me clarifying questions. It did, and we refined the requirements over 3 chat messages. It then created the entire program, including 6 different files. Next steps would be for it to run the code and test it, and wait for my feedback only after it thinks it's passed all tests. Is this how openhands works? The documentation seems to imply you have to keep asking it to do things, like a copilot with extra steps.

**Comment by enyst** [comment]
Yes, `openhands` can run non-interactively to do a task until it thinks it finished it, or until it hits a configurable limit (you can set a maximum number of steps, for example, so that it doesn't go on too long; default is 100 I believe).

Best for non-interactive, is to run headless via `main.py` (https://docs.all-hands.dev/modules/usage/how-to/headless-mode)

The main agent does have an interactivity that you may not want: it's the LLM who decides if it wants to ask the user something. But when running headless, we give it some default text from the user ("continue") in that case.
